# Dependencies
markdown:         kramdown
highlighter:      rouge
extensions:       [fenced_code_blocks]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'WholeShebang.net Blog'
tagline:          'Technical Support and Solutions'
description:      "Updates and Notices about Future Services"
url:              https:/wholeshebang.net
baseurl:          /

author:
  name:           'ardentj'
  url:            https://beatrix.io

paginate:         5

# Custom vars
version:          2.1.0

excerpt_separator:  <!--more-->

github:
  repo:           https://github.com/ardentj

social:
  twitter:        http://twitter.com/beatrix_IO

gems:             [jekyll-paginate]
